### ISSUE TITLE
is there anything miss?

### ISSUE THREAD

**Issue by RockyQLuo** [shili2017/CONNECT-AXI#1]
[error] firrtl.transforms.BlackBoxNotFoundException: BlackBox '/afs/ece.cmu.edu/support/altera/release/pro-19.3.0.222/quartus/eda/sim_lib/altera_mf.v' not found. Did you misspell it? Is it in src/{main,test}/resources?
[error] /afs/ece.cmu.edu/support/altera/release/pro-19.3.0.222/quartus/eda/sim_lib/altera_mf.v (No such file or directory)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) firrtl.transforms.BlackBoxNotFoundException: BlackBox '/afs/ece.cmu.edu/support/altera/release/pro-19.3.0.222/quartus/eda/sim_lib/altera_mf.v' not found. Did you misspell it? Is it in src/{main,test}/resources?
[error] /afs/ece.cmu.edu/support/altera/release/pro-19.3.0.222/quartus/eda/sim_lib/altera_mf.v (No such file or directory)

**Comment by shili2017** [comment]
Please replace this with your own FIFO IP path, or just set USE_FIFO_IP to 0. Thanks.
