### ISSUE TITLE
question about GetSrcFromPacket

### ISSUE THREAD

**Issue by RockyQLuo** [shili2017/CONNECT-AXI#2]
Hello, I am a rookie reading your source code. I just want to ask if you have tested your code correctly?
I found that:
```scala
object GetSrcFromPacket {
  def apply(packet: UInt)(implicit p: NetworkConfigs): UInt = {
    assert(packet.getWidth == p.PACKET_WIDTH)
    packet(p.PACKET_WIDTH - p.META_WIDTH + p.SRC_BITS - 1, p.PACKET_WIDTH - p.META_WIDTH)
  }
}
```
in your AXI4Packet.scala
but it seems that 
```scala
META_WIDTH = SRC_BITS + DEST_BITS + VC_BITS + 2
PACKET_WIDTH=AXI4PacketDataWidth() + META_WIDTH
```
therefore DEVICE_ID may not be reached i think?
below is w_packet for example
![image](https://github.com/user-attachments/assets/7fa9de90-1eee-4f8b-899e-c96e15195c25)

sorry！i got something wrong，i found object Assemble now

**Comment by luoqi-1** [comment]
> Hello, I am a rookie reading your source code. I just want to ask if you have tested your code correctly? I found that:
> 
> ```scala
> object GetSrcFromPacket {
>   def apply(packet: UInt)(implicit p: NetworkConfigs): UInt = {
>     assert(packet.getWidth == p.PACKET_WIDTH)
>     packet(p.PACKET_WIDTH - p.META_WIDTH + p.SRC_BITS - 1, p.PACKET_WIDTH - p.META_WIDTH)
>   }
> }
> ```
> 
> in your AXI4Packet.scala but it seems that
> 
> ```scala
> META_WIDTH = SRC_BITS + DEST_BITS + VC_BITS + 2
> PACKET_WIDTH=AXI4PacketDataWidth() + META_WIDTH
> ```
> 
> therefore DEVICE_ID may not be reached i think? below is w_packet for example ![image](https://private-user-images.githubusercontent.com/119088365/370739305-7fa9de90-1eee-4f8b-899e-c96e15195c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzI1MjQsIm5iZiI6MTcyNzI3MjIyNCwicGF0aCI6Ii8xMTkwODgzNjUvMzcwNzM5MzA1LTdmYTlkZTkwLTFlZWUtNGY4Yi04OTllLWM5NmUxNTE5NWMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMzUwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWRhNzE4Mjk4Y2I4MWE2OTExMDI2ZmI5NWNiNzUwMTEyYWZhNThmM2RiODQ4MmI1ODVhNDZlNDc1YzE4YzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s9_fHf4vx75L17zgoAI2wthD2KsRxXknnFyb4Q3zaL8)

**Comment by luoqi-1** [comment]
i didnt find the usage of Assemble, not sure if w_packet  is right or not
